---

- name: Install, enable, and start services

  systemd:

    name: "{{ item }}"

    enabled: yes

    state: started

  loop: "{{ services }}"
  
- name: Ensure required packages are installed

  package:

    name: "{{ item }}"

    state: present

  loop: "{{ services }}"

  notify: restart services


